export enum UserRoles {
  BASIC_EMPLOYEE = 'basicEmployee',
  FRANCHISE_EMPLOYEE = 'franchiseEmployee',
  ADMIN = 'admin',
  BRANCH_EMPLOYEE = 'branchEmployee',
  VM_MANAGER = 'vmManager',
  TENDER_MANAGER = 'tenderManager',
  SALES_MANAGER = 'salesManager',
  RESPONSIBLE_FOR_NEW_VENDORS = 'responsibleForNewVendors',
  RDEP_MANAGER = 'rdepManager',
  PROJECT_MANAGER = 'projectManager',
  PRODUCTION_MANAGER = 'productionManager',
  LQA_MANAGER = 'lqaManager',
  KPI_MANAGER = 'kpiManager',
  INCOMING_LEAD_MANAGER = 'incomingLeadManager',
  DTP_QA_MANAGER = 'dtpQaManager',
  DTP_MANAGER = 'dtpManager',
  CRM_MANAGER = 'crmManager',
  COURIER = 'courier',
  CLIENT_MANAGER = 'clientManager',
  BS_MANAGER = 'bsManager',
  CLIENT_USER = 'clientUser',
  CLIENT_SUPER_USER = 'clientSuperUser',
  FREELANCER = 'freelancer',
  ANALYTICS = 'analytics',
  EXPERT_CENTER = 'expertCenter',
}
